import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { messages } from '../src/i18n'

async function accessibilityIssues(page: Page) {
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  return result.violations.map((violation) => ({
    rule: violation.id,
    nodes: violation.nodes.map((node) => ({ target: node.target, message: node.failureSummary })),
  }))
}

test('flujo completo: convertir desde CDMX, añadir, editar, persistir y vaciar', async ({ page }, testInfo) => {
  const errors: string[] = []
  const externalRequests: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('request', (request) => {
    if (new URL(request.url()).hostname !== '127.0.0.1') externalRequests.push(request.url())
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Un mismo instante. Muchos lugares.')
  await expect(page.getByRole('article')).toHaveCount(3)
  await page.screenshot({ path: testInfo.outputPath('dashboard.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)

  await page.getByRole('button', { name: 'Convertir horario', exact: true }).click()
  await page.getByLabel('Fecha en CDMX').fill('2026-12-31')
  await page.getByLabel('Hora en CDMX (24 h)').fill('23:30')
  await page.getByRole('button', { name: 'Convertir en todos los relojes' }).click()
  const tokyo = page.getByRole('article', { name: 'Reloj de Tokio', exact: true })
  await expect(tokyo).toContainText('14:30')
  await expect(tokyo).toContainText('1 de enero de 2027')
  await expect(tokyo).toContainText('+1 día')

  await page.getByRole('button', { name: 'Añadir reloj', exact: true }).click()
  await expect(page.getByLabel('Buscar ubicación')).toBeFocused()
  await page.getByLabel('Buscar ubicación').fill('nepal')
  await page.getByLabel(/Ciudad o zona/).selectOption('Asia/Kathmandu')
  await page.getByLabel('Etiqueta de cliente').fill('Cliente Nepal')
  await page.getByRole('dialog').getByRole('button', { name: 'Añadir reloj' }).click()
  const nepal = page.getByRole('article', { name: 'Reloj de Katmandú, Cliente Nepal', exact: true })
  await expect(nepal).toContainText('11:15')
  await expect(nepal).toContainText('+11 h 45 min vs. CDMX')
  await nepal.getByRole('button', { name: 'Editar reloj de Katmandú' }).click()
  await page.getByLabel('Etiqueta de cliente').fill('Soporte Nepal')
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await page.getByRole('button', { name: '12 h', exact: true }).click()
  await page.reload()
  const nextPage = page.getByRole('button', { name: 'Relojes siguientes' })
  if (await nextPage.count()) await nextPage.click()
  await expect(page.getByText('Soporte Nepal', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '12 h', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Ahora', exact: true })).toHaveAttribute('aria-pressed', 'true')

  await page.getByRole('button', { name: 'Añadir reloj', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Añadir reloj', exact: true })).toBeFocused()
  while (await page.getByRole('button', { name: /Quitar reloj/ }).count()) {
    await page.getByRole('button', { name: /Quitar reloj/ }).first().click()
  }
  await page.reload()
  await expect(page.getByText('Tu mundo empieza aquí')).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(0)
  expect(errors).toEqual([])
  expect(externalRequests).toEqual([])
})

test('errores históricos y entrada inválida no modifican el último resultado', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Convertir horario', exact: true }).click()
  for (const [date, time] of [['2022-04-03', '02:30'], ['2022-10-30', '01:30']]) {
    await page.getByLabel('Fecha en CDMX').fill(date)
    await page.getByLabel('Hora en CDMX (24 h)').fill(time)
    await page.getByRole('button', { name: 'Convertir en todos los relojes' }).click()
    await expect(page.getByRole('alert')).toContainText('ambigua o no existió')
  }
  await page.getByLabel('Fecha en CDMX').fill('')
  await page.getByRole('button', { name: 'Convertir en todos los relojes' }).click()
  await expect(page.getByRole('alert')).toContainText('fecha y una hora completas')
  await page.getByRole('button', { name: 'Volver a ahora' }).click()
  await expect(page.getByRole('button', { name: 'Ahora', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('preserva datos inválidos y avisa si el almacenamiento está bloqueado', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('meridiano.preferences.v1', 'original sin modificar'))
  await page.reload()
  await expect(page.getByRole('alert')).toContainText('datos originales')
  await page.getByRole('button', { name: '12 h', exact: true }).click()
  expect(await page.evaluate(() => localStorage.getItem('meridiano.preferences.v1'))).toBe('original sin modificar')
  await page.getByRole('button', { name: 'Guardar esta configuración en la app' }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)

  await page.addInitScript(() => {
    Storage.prototype.setItem = () => { throw new DOMException('Blocked', 'SecurityError') }
  })
  await page.reload()
  await page.getByRole('button', { name: '24 h', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('No se pudieron guardar')
})

test('accesibilidad y tamaño mínimo: contraste, etiquetas, teclado y relojes sin recortes', async ({ page }) => {
  await page.goto('/')
  expect(await accessibilityIssues(page)).toEqual([])
  await page.getByRole('button', { name: '12 h', exact: true }).click()
  await page.setViewportSize({ width: 320, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(await page.locator('.time-display').evaluateAll((elements) => elements.every((element) => element.scrollWidth <= element.clientWidth))).toBe(true)
  await page.getByRole('button', { name: 'Convertir horario', exact: true }).click()
  expect(await accessibilityIssues(page)).toEqual([])
  await page.getByRole('button', { name: 'Añadir reloj', exact: true }).click()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Cerrar diálogo' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  // Scrollable native dialogs add a container stop before browser chrome.
  const dialog = page.getByRole('dialog')
  if (await dialog.evaluate((element) => element === document.activeElement)) await page.keyboard.press('Shift+Tab')
  // Native dialogs can visit browser chrome, but must not focus the inert page.
  expect(await page.evaluate(() => !document.hasFocus() || Boolean(document.querySelector('dialog')?.contains(document.activeElement)))).toBe(true)
  if (!(await page.evaluate(() => document.hasFocus()))) await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Añadir reloj' })).toBeFocused()
  expect(await accessibilityIssues(page)).toEqual([])
})

test('tema: datos anteriores, sistema y elección explícita persistente mediante teclado', async ({ page }) => {
  const legacy = { version: 1, hourCycle: '12', clocks: [{ id: 'legacy', zone: 'Asia/Kathmandu', label: 'Cliente anterior' }] }
  await page.addInitScript((preferences) => {
    if (localStorage.getItem('meridiano.preferences.v1') === null) {
      localStorage.setItem('meridiano.preferences.v1', JSON.stringify(preferences))
    }
  }, legacy)
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByText('Cliente anterior', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '12 h', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('meridiano.preferences.v1')!))).toEqual(legacy)
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')

  const toggle = page.getByRole('button', { name: 'Cambiar a modo claro' })
  await toggle.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.emulateMedia({ colorScheme: 'light' })
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('meridiano.preferences.v1')!))).toEqual({ ...legacy, theme: 'light' })
  await page.getByRole('button', { name: 'Cambiar a modo oscuro' }).focus()
  await page.keyboard.press('Space')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('article')).toHaveCount(1)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('meridiano.preferences.v1')!))).toEqual({ ...legacy, theme: 'dark' })
})

test('tema: aplica la elección antes de descargar React', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'light' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Cambiar a modo oscuro' }).click()
  let release = () => {}
  const gate = new Promise<void>((resolve) => { release = resolve })
  await page.route('**/src/main.tsx', async (route) => { await gate; await route.continue() })
  const navigation = page.reload({ waitUntil: 'domcontentloaded' })
  try {
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await expect(page.locator('#root')).toBeEmpty()
    await expect(page.locator('html')).toHaveCSS('background-color', 'rgb(17, 27, 25)')
    await expect(page.locator('html')).toHaveCSS('color-scheme', 'dark')
  } finally {
    release()
    await navigation
    await page.unroute('**/src/main.tsx')
  }
  await expect(page.getByRole('button', { name: 'Cambiar a modo claro' })).toBeVisible()
})

for (const language of ['es', 'en'] as const) {
  for (const theme of ['light', 'dark'] as const) {
  test(`tema ${theme}, idioma ${language}: contraste, conversión, diálogo y errores en toda la interfaz`, async ({ page }, testInfo) => {
    const t = messages(language)
    await page.emulateMedia({ colorScheme: theme })
    await page.goto('/')
    if (language === 'en') await page.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }).click()
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
    await expect(page.locator('html')).toHaveAttribute('lang', language)
    expect(await accessibilityIssues(page)).toEqual([])
    await page.getByRole('button', { name: t.convertMode, exact: true }).click()
    await page.getByLabel(t.dateLabel).fill('2026-12-31')
    await page.getByLabel(t.timeLabel).fill('23:30')
    await page.getByRole('button', { name: t.convertAll }).click()
    await expect(page.getByRole('article', { name: language === 'en' ? 'Clock for Tokyo' : 'Reloj de Tokio', exact: true })).toContainText('14:30')
    await expect(page.getByLabel(t.dateLabel)).toHaveCSS('color-scheme', theme)
    await page.screenshot({ path: testInfo.outputPath(`meridiano-${theme}-${language}.png`), fullPage: true })
    await page.getByLabel(t.dateLabel).fill('')
    await page.getByRole('button', { name: t.convertAll }).click()
    await expect(page.getByRole('alert')).toBeVisible()
    expect(await accessibilityIssues(page)).toEqual([])

    await page.getByRole('button', { name: t.addClock, exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: t.addClock }).click()
    expect(await accessibilityIssues(page)).toEqual([])
    await page.getByLabel(t.searchLocation).fill('Nepal')
    await page.getByLabel(t.cityOrZone).selectOption('Asia/Kathmandu')
    await page.getByLabel(t.clientLabel).fill('Cliente de prueba')
    await page.screenshot({ path: testInfo.outputPath(`meridiano-${theme}-${language}-dialog.png`), fullPage: true })
    await page.getByRole('dialog').getByRole('button', { name: t.addClock }).click()
    await expect(page.getByRole('article', { name: language === 'en' ? 'Clock for Kathmandu, Cliente de prueba' : 'Reloj de Katmandú, Cliente de prueba' })).toContainText('11:15')

    await page.getByRole('button', { name: '12 h', exact: true }).click()
    await page.setViewportSize({ width: 320, height: 800 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    expect(await page.locator('.time-display').evaluateAll((elements) => elements.every((element) => element.scrollWidth <= element.clientWidth))).toBe(true)
    await page.getByRole('button', { name: t.returnNow }).click()
    const removeButtons = page.getByRole('button', { name: language === 'en' ? /Remove clock/ : /Quitar reloj/ })
    while (await removeButtons.count()) {
      await removeButtons.first().click()
    }
    await expect(page.getByText(t.emptyTitle)).toBeVisible()
    expect(await accessibilityIssues(page)).toEqual([])
    await page.evaluate(() => {
      Storage.prototype.setItem = () => { throw new DOMException('Blocked', 'SecurityError') }
    })
    await page.getByRole('button', { name: '24 h', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText(t.storageWriteError)
    expect(await accessibilityIssues(page)).toEqual([])
  })
  }
}

test('idioma: cambia sin recargar ni perder la conversión y conserva tema, etiquetas y formato', async ({ page }) => {
  const original = { version: 1, theme: 'light', hourCycle: '12', clocks: [{ id: 'legacy', zone: 'Europe/London', label: 'Cliente Español · 日本' }] }
  await page.addInitScript((preferences) => {
    if (!localStorage.getItem('meridiano.preferences.v1')) localStorage.setItem('meridiano.preferences.v1', JSON.stringify(preferences))
  }, original)
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('lang', 'es')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('meridiano.preferences.v1')!))).toEqual(original)
  await page.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('One shared moment. Many places.')
  await expect(page).toHaveTitle('Meridiano · World clocks')
  await expect(page.getByText('Cliente Español · 日本', { exact: true })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Convert time', exact: true }).click()
  await page.getByLabel('Date in Mexico City').fill('2026-12-31')
  await page.getByLabel('Time in Mexico City (24 h)').fill('23:30')
  await page.getByRole('button', { name: 'Convert across all clocks' }).click()
  const clock = page.getByRole('article')
  await expect(clock).toContainText('05:30')
  await expect(clock).toContainText('AM')
  await expect(clock).toContainText('Friday, January 1, 2027')
  await page.getByRole('button', { name: 'ES / EN: Switch to Spanish' }).click()
  await expect(page.getByLabel('Fecha en CDMX')).toHaveValue('2026-12-31')
  await expect(clock).toContainText('05:30')
  await expect(clock).toContainText('viernes, 1 de enero de 2027')
  await page.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }).click()
  await page.getByRole('button', { name: 'Switch to dark mode' }).click()
  await page.getByRole('button', { name: '24 h', exact: true }).click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('button', { name: '24 h', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('meridiano.preferences.v1')!))).toEqual({ ...original, theme: 'dark', hourCycle: '24', language: 'en' })
})

test('idioma: búsqueda bilingüe, errores ya visibles y confirmaciones traducidas', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Convertir horario', exact: true }).click()
  await page.getByLabel('Fecha en CDMX').fill('2022-10-30')
  await page.getByLabel('Hora en CDMX (24 h)').fill('01:30')
  await page.getByRole('button', { name: 'Convertir en todos los relojes' }).click()
  await expect(page.getByRole('alert')).toContainText('ambigua o no existió')
  await page.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }).click()
  await expect(page.getByRole('alert')).toContainText('ambiguous or did not exist')
  await page.getByRole('button', { name: 'Add clock', exact: true }).click()
  await page.getByLabel('Search location').fill('No-city-matches')
  await expect(page.getByText('No matches. Try another city, country, IANA zone, or an offset such as GMT+2 or UTC+05:30.')).toBeVisible()
  await page.getByLabel('Search location').fill('Nueva York')
  await expect(page.getByRole('option', { name: 'New York · United States — America/New_York' })).toHaveCount(1)
  await page.getByLabel('City or time zone').selectOption('America/New_York')
  await page.getByLabel('Client label').fill('Equipo de México')
  await page.getByRole('dialog').getByRole('button', { name: 'Add clock' }).click()
  await expect(page.getByRole('article', { name: 'Clock for New York, Equipo de México' })).toBeVisible()
  await expect(page.getByText('Clock for New York added.', { exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: 'ES / EN: Switch to Spanish' }).click()
  await expect(page.getByRole('article', { name: 'Reloj de Nueva York, Equipo de México' })).toBeVisible()
  await expect(page.getByText('Reloj de Nueva York añadido.', { exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: 'Volver a ahora' }).click()
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Blocked', 'SecurityError') } })
  await page.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }).click()
  await expect(page.getByRole('alert')).toContainText('Your changes could not be saved')
  await page.getByRole('button', { name: 'ES / EN: Switch to Spanish' }).click()
  await expect(page.getByRole('alert')).toContainText('No se pudieron guardar')
})

for (const language of ['es', 'en'] as const) {
  test(`busqueda GMT: offsets por fecha y relojes IANA en ${language}`, async ({ page }) => {
    const t = messages(language)
    await page.goto('/')
    if (language === 'en') await page.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }).click()
    await page.getByRole('button', { name: t.convertMode, exact: true }).click()
    await page.getByLabel(t.dateLabel).fill('2026-07-15')
    await page.getByLabel(t.timeLabel).fill('09:00')
    await page.getByRole('button', { name: t.convertAll }).click()
    await page.getByRole('button', { name: t.addClock, exact: true }).click()
    await page.getByLabel(t.searchLocation).fill('Gmt+2')
    await expect(page.getByRole('option', { name: /Europe\/Berlin/ })).toHaveCount(1)
    await expect(page.getByRole('option', { name: /Europe\/London/ })).toHaveCount(0)
    await page.getByLabel(t.cityOrZone).selectOption('Europe/Berlin')
    await expect(page.locator('#selected-zone')).toContainText('UTC+02:00')
    expect(await accessibilityIssues(page)).toEqual([])
    await page.getByRole('dialog').getByRole('button', { name: t.addClock }).click()
    const berlin = page.getByRole('article', { name: language === 'en' ? 'Clock for Berlin' : 'Reloj de Berlín', exact: true })
    await expect(berlin).toContainText('17:00')
    await expect(berlin).toContainText('UTC+02:00')
    await page.getByLabel(t.dateLabel).fill('2026-01-15')
    await page.getByRole('button', { name: t.convertAll }).click()
    await expect(berlin).toContainText('16:00')
    await expect(berlin).toContainText('UTC+01:00')
    await page.getByRole('button', { name: t.addClock, exact: true }).click()
    await page.getByLabel(t.searchLocation).fill('UTC+02:00')
    await expect(page.getByRole('option', { name: /Europe\/Berlin/ })).toHaveCount(0)
    await expect(page.getByRole('option', { name: /Africa\/Johannesburg/ })).toHaveCount(1)
    await page.getByLabel(t.searchLocation).fill('UTC+05:45')
    await expect(page.getByRole('option', { name: /Asia\/Kathmandu/ })).toHaveCount(1)
    await page.getByLabel(t.searchLocation).fill('GMT+99')
    await expect(page.getByText(t.noResults)).toBeVisible()
  })
}

test('Romania: encuentra Bucarest y ajusta GMT+3 de septiembre a GMT+2 de invierno', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Convertir horario', exact: true }).click()
  await page.getByLabel('Fecha en CDMX').fill('2026-09-22')
  await page.getByLabel('Hora en CDMX (24 h)').fill('09:00')
  await page.getByRole('button', { name: 'Convertir en todos los relojes' }).click()
  await page.getByRole('button', { name: 'Añadir reloj', exact: true }).click()
  await page.getByLabel('Buscar ubicación').fill('Romania')
  await expect(page.getByRole('option', { name: 'Bucarest · Rumanía — Europe/Bucharest' })).toHaveCount(1)
  await page.getByLabel('Ciudad o zona').selectOption('Europe/Bucharest')
  await expect(page.locator('#selected-zone')).toContainText('UTC+03:00')
  await page.getByLabel('Etiqueta de cliente').fill('Cliente Romania')
  await page.getByRole('dialog').getByRole('button', { name: 'Añadir reloj' }).click()
  await expect(page.getByRole('article', { name: 'Reloj de Bucarest, Cliente Romania' })).toContainText('18:00')
  await page.getByLabel('Fecha en CDMX').fill('2026-01-15')
  await page.getByRole('button', { name: 'Convertir en todos los relojes' }).click()
  await expect(page.getByRole('article', { name: 'Reloj de Bucarest, Cliente Romania' })).toContainText('UTC+02:00')
  await expect(page.getByRole('article', { name: 'Reloj de Bucarest, Cliente Romania' })).toContainText('17:00')
  await page.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }).click()
  await expect(page.getByRole('article', { name: 'Clock for Bucharest, Cliente Romania' })).toBeVisible()
  await page.getByRole('button', { name: 'Add clock', exact: true }).click()
  await page.getByLabel('Search location').fill('GMT+2')
  await expect(page.getByRole('option', { name: 'Bucharest · Romania — Europe/Bucharest' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Cancel' }).click()
  await page.reload()
  const nextPage = page.getByRole('button', { name: 'Next clocks' })
  if (await nextPage.count()) await nextPage.click()
  await expect(page.getByRole('article', { name: 'Clock for Bucharest, Cliente Romania' })).toBeVisible()
})

test('catálogo mundial: regiones, países, DST de media hora y persistencia sin red externa', async ({ page }) => {
  const externalRequests: string[] = []
  const errors: string[] = []
  page.on('request', (request) => {
    if (new URL(request.url()).hostname !== '127.0.0.1') externalRequests.push(request.url())
  })
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Convertir horario', exact: true }).click()
  await page.getByLabel('Fecha en CDMX').fill('2026-01-15')
  await page.getByLabel('Hora en CDMX (24 h)').fill('09:00')
  await page.getByRole('button', { name: 'Convertir en todos los relojes' }).click()
  await page.getByRole('button', { name: 'Añadir reloj', exact: true }).click()
  expect(await page.getByRole('option').count()).toBeGreaterThan(400)
  await page.getByLabel('Buscar ubicación').fill('Europa')
  await expect(page.getByRole('option', { name: /Europe\/Warsaw/ })).toHaveCount(1)
  await page.getByLabel('Buscar ubicación').fill('Afganistan')
  await expect(page.getByRole('option', { name: /Asia\/Kabul/ })).toHaveCount(1)
  await page.getByLabel('Buscar ubicación').fill('Lord Howe')
  await page.getByLabel('Ciudad o zona').selectOption('Australia/Lord_Howe')
  await expect(page.locator('#selected-zone')).toContainText('UTC+11:00')
  await page.getByLabel('Etiqueta de cliente').fill('Cliente isla')
  await page.getByRole('dialog').getByRole('button', { name: 'Añadir reloj' }).click()
  const lordHowe = page.getByRole('article', { name: 'Reloj de Isla Lord Howe, Cliente isla' })
  await expect(lordHowe).toContainText('02:00')
  await expect(lordHowe).toContainText('16 de enero de 2026')
  await page.getByLabel('Fecha en CDMX').fill('2026-07-15')
  await page.getByRole('button', { name: 'Convertir en todos los relojes' }).click()
  await expect(lordHowe).toContainText('01:30')
  await expect(lordHowe).toContainText('UTC+10:30')

  await page.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }).click()
  await page.getByRole('button', { name: 'Add clock', exact: true }).click()
  await page.getByLabel('Search location').fill('French Polynesia')
  await expect(page.getByRole('option', { name: /Pacific\/Marquesas/ })).toHaveCount(1)
  await page.getByLabel('Search location').fill('UTC-09:30')
  await page.getByLabel('City or time zone').selectOption('Pacific/Marquesas')
  await expect(page.locator('#selected-zone')).toContainText('UTC−09:30')
  expect(await accessibilityIssues(page)).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('dialog').getByRole('button', { name: 'Add clock' }).click()
  await expect(page.getByRole('article', { name: 'Clock for Marquesas Islands' })).toContainText('05:30')
  await page.reload()
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('meridiano.preferences.v1')!))
  expect(persisted.clocks).toHaveLength(5)
  expect(persisted.clocks.at(-2)).toMatchObject({ zone: 'Australia/Lord_Howe', label: 'Cliente isla' })
  expect(persisted.clocks.at(-1)).toMatchObject({ zone: 'Pacific/Marquesas' })
  const seen = new Set<string>()
  do {
    for (const name of await page.getByRole('article').evaluateAll((elements) => elements.map((element) => element.getAttribute('aria-label')!))) seen.add(name)
    const next = page.getByRole('button', { name: 'Next clocks' })
    if (!await next.count() || await next.isDisabled()) break
    await next.click()
  } while (seen.size <= 5)
  expect(seen.size).toBe(5)
  expect(seen.has('Clock for Lord Howe Island, Cliente isla')).toBe(true)
  await expect(page.getByRole('article', { name: 'Clock for Marquesas Islands' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit clock for Marquesas Islands' }).click()
  await expect(page.getByLabel('City or time zone')).toHaveValue('Pacific/Marquesas')
  await page.getByLabel('Client label').fill('Equipo del Pacifico')
  await page.getByRole('button', { name: 'Save changes' }).click()
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('meridiano.preferences.v1')!))
  expect(stored.clocks.at(-1)).toMatchObject({ zone: 'Pacific/Marquesas', label: 'Equipo del Pacifico' })
  expect(externalRequests).toEqual([])
  expect(errors).toEqual([])
})
