import { StrictMode } from 'react'
import { fireEvent, render, screen, within } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import App from './App'
import { messages } from './i18n'
import { defaultPreferences, parsePreferences, STORAGE_KEY } from './storage'

describe('dashboard', () => {
  it.each([
    ['es', 'light'], ['es', 'dark'], ['en', 'light'], ['en', 'dark'],
  ] as const)('omite los bloques inferiores y conserva controles y accesibilidad en %s/%s', (language, theme) => {
    const t = messages(language)
    const preferences = { ...defaultPreferences(), language, theme }
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(preferences))
    render(<App />)
    expect(document.querySelector('.add-clock-card, .help-strip')).toBeNull()
    expect(screen.getAllByRole('article')).toHaveLength(3)
    for (const card of screen.getAllByRole('article')) {
      expect(card.querySelector('.day-icon')).toBeNull()
      expect(within(card).getByText((text) => text === t.daytime || text === t.nighttime)).toHaveClass('sr-only')
      expect(within(card).getAllByRole('button')).toHaveLength(2)
    }
    expect(screen.getByRole('contentinfo')).toHaveTextContent(t.privacyDescription)
    expect(window.localStorage.getItem(STORAGE_KEY)).toBe(JSON.stringify(preferences))
    fireEvent.click(screen.getByRole('button', { name: t.addClock }))
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: t.cancel }))
    fireEvent.click(screen.getByRole('button', { name: t.convertMode }))
    expect(screen.getByLabelText(t.dateLabel)).toHaveAccessibleDescription(t.precisionDescription)
    expect(screen.getByLabelText(t.timeLabel)).toHaveAccessibleDescription(t.precisionDescription)
    expect(document.getElementById('conversion-note')).toHaveClass('sr-only')
  })

  it('añade, conserva y elimina un caso opcional sin alterar el cliente o su zona', () => {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...defaultPreferences(), clocks: [] }))
    const first = render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Añadir reloj' }))
    expect(screen.getByLabelText(/Número de caso/)).toHaveAttribute('type', 'text')
    expect(screen.getByLabelText(/Número de caso/)).toHaveAttribute('maxlength', '60')
    expect(screen.getByLabelText(/Número de caso/)).not.toBeRequired()
    fireEvent.change(screen.getByLabelText('Buscar ubicación'), { target: { value: 'Romania' } })
    fireEvent.change(screen.getByLabelText(/Ciudad o zona/), { target: { value: 'Europe/Bucharest' } })
    fireEvent.change(screen.getByLabelText(/Número de caso/), { target: { value: '  0000123456789012  ' } })
    fireEvent.change(screen.getByLabelText(/Etiqueta de cliente/), { target: { value: 'Equipo Acme' } })
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Añadir reloj' }))
    expect(screen.getByText('0000123456789012')).toHaveClass('case-badge')
    expect(document.querySelector('.clock-card .case-label')).toBeNull()
    const original = parsePreferences(window.localStorage.getItem(STORAGE_KEY)!).clocks[0]
    expect(original).toEqual({ id: expect.any(String), zone: 'Europe/Bucharest', label: 'Equipo Acme', caseNumber: '0000123456789012' })
    first.unmount()
    render(<App />)
    expect(screen.getByText('0000123456789012')).toHaveClass('case-badge')
    fireEvent.click(screen.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }))
    expect(screen.getByText('0000123456789012')).toHaveClass('case-badge')
    expect(document.querySelector('.clock-card .case-label')).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Edit clock for Bucharest' }))
    expect(screen.getByLabelText(/Case number/)).toHaveValue('0000123456789012')
    fireEvent.change(screen.getByLabelText(/Case number/), { target: { value: 'SR-0042' } })
    fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(screen.getByText('0000123456789012')).toBeInTheDocument()
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!).clocks[0]).toEqual(original)
    fireEvent.click(screen.getByRole('button', { name: 'Compare' }))
    expect(within(screen.getByRole('rowheader', { name: /Bucharest/ })).getByText('0000123456789012')).toHaveClass('case-badge')
    expect(screen.getByText('Case').nextElementSibling).toBe(screen.getByText('0000123456789012'))
    fireEvent.click(screen.getByRole('button', { name: 'Edit clock for Bucharest' }))
    fireEvent.change(screen.getByLabelText(/Case number/), { target: { value: 'SR-0042' } })
    fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
    expect(screen.getByText('SR-0042')).toHaveClass('case-badge')
    fireEvent.click(screen.getByRole('button', { name: 'Edit clock for Bucharest' }))
    fireEvent.change(screen.getByLabelText(/Case number/), { target: { value: '   ' } })
    fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
    expect(document.querySelector('.case-badge')).toBeNull()
    expect(document.querySelector('.case-label')).toBeNull()
    const { caseNumber: removed, ...withoutCase } = original
    expect(removed).toBe('0000123456789012')
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!).clocks[0]).toEqual(withoutCase)
  })

  it('permite añadir un caso a un reloj anterior sin extraer ni modificar su etiqueta', () => {
    const legacy = { id: 'legacy', zone: 'Europe/Bucharest', label: '000123456789 - Cliente' }
    const raw = JSON.stringify({ ...defaultPreferences(), clocks: [legacy] })
    window.localStorage.setItem(STORAGE_KEY, raw)
    render(<App />)
    expect(document.querySelector('.case-badge')).toBeNull()
    expect(window.localStorage.getItem(STORAGE_KEY)).toBe(raw)
    fireEvent.click(screen.getByRole('button', { name: 'Editar reloj de Bucarest' }))
    expect(screen.getByLabelText(/Número de caso/)).toHaveValue('')
    fireEvent.change(screen.getByLabelText(/Número de caso/), { target: { value: '000123456789' } })
    fireEvent.click(screen.getByRole('button', { name: 'Guardar cambios' }))
    expect(screen.getByText(legacy.label)).toBeInTheDocument()
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!).clocks[0]).toEqual({ ...legacy, caseNumber: '000123456789' })
  })

  it('avisa de un fallo al guardar el caso y conserva el original en almacenamiento', () => {
    const legacy = { id: 'legacy', zone: 'America/New_York', label: 'Cliente' }
    const raw = JSON.stringify({ ...defaultPreferences(), clocks: [legacy] })
    window.localStorage.setItem(STORAGE_KEY, raw)
    render(<App />)
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('Full', 'QuotaExceededError') })
    fireEvent.click(screen.getByRole('button', { name: 'Editar reloj de Nueva York' }))
    fireEvent.change(screen.getByLabelText(/Número de caso/), { target: { value: '00042' } })
    fireEvent.click(screen.getByRole('button', { name: 'Guardar cambios' }))
    expect(screen.getByRole('alert')).toHaveTextContent('No se pudieron guardar')
    expect(screen.getByText('00042')).toHaveClass('case-badge')
    expect(window.localStorage.getItem(STORAGE_KEY)).toBe(raw)
  })

  it('añade Eastern Time desde ET y conserva nombres, etiqueta y reglas IANA al recargar', () => {
    const original = { ...defaultPreferences(), theme: 'dark' as const, language: 'en' as const, clocks: [] }
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(original))
    const view = render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Add clock' }))
    fireEvent.change(screen.getByLabelText('Search location'), { target: { value: 'ET' } })
    expect(screen.getByRole('group', { name: 'Eastern Time (ET / EST / EDT)' })).toBeInTheDocument()
    expect(screen.queryByRole('option', { name: /Bucharest/ })).not.toBeInTheDocument()
    fireEvent.change(screen.getByLabelText(/City or time zone/), { target: { value: 'America/New_York' } })
    expect(document.getElementById('selected-zone')).toHaveTextContent('Eastern Time (ET / EST / EDT)')
    fireEvent.change(screen.getByLabelText(/Client label/), { target: { value: 'Equipo ET' } })
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Add clock' }))
    const saved = parsePreferences(window.localStorage.getItem(STORAGE_KEY)!)
    expect(saved.clocks).toEqual([{ id: expect.any(String), zone: 'America/New_York', label: 'Equipo ET' }])
    expect(saved.theme).toBe('dark')
    view.unmount()
    render(<App />)
    const card = within(screen.getByRole('article', { name: 'Clock for New York, Equipo ET' }))
    expect(card.getByText('Eastern Time (ET / EST / EDT)')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'ES / EN: Switch to Spanish' }))
    expect(screen.getByRole('article', { name: 'Reloj de Nueva York, Equipo ET' })).toHaveTextContent('ET / EST / EDT')
    expect(document.documentElement).toHaveAttribute('data-theme', 'dark')
    fireEvent.click(screen.getByRole('button', { name: 'Comparador' }))
    expect(screen.getByRole('rowheader', { name: /Nueva York/ })).toHaveTextContent('ET / EST / EDT')
  })

  it('busca GMT+2 desde el conversor y guarda la zona IANA, no un offset fijo', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Convertir horario' }))
    fireEvent.change(screen.getByLabelText('Fecha en CDMX'), { target: { value: '2026-07-15' } })
    fireEvent.change(screen.getByLabelText('Hora en CDMX (24 h)'), { target: { value: '09:00' } })
    fireEvent.click(screen.getByRole('button', { name: 'Convertir en todos los relojes' }))
    fireEvent.click(screen.getByRole('button', { name: 'Añadir reloj' }))
    fireEvent.change(screen.getByLabelText('Buscar ubicación'), { target: { value: 'Gmt+2' } })
    expect(screen.getByRole('option', { name: 'Berlín · Alemania — Europe/Berlin' })).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText(/Ciudad o zona/), { target: { value: 'Europe/Berlin' } })
    expect(screen.getByText(/UTC\+02:00 en el instante mostrado/)).toBeInTheDocument()
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Añadir reloj' }))
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!).clocks.at(-1)?.zone).toBe('Europe/Berlin')
    fireEvent.change(screen.getByLabelText('Fecha en CDMX'), { target: { value: '2026-01-15' } })
    fireEvent.click(screen.getByRole('button', { name: 'Convertir en todos los relojes' }))
    expect(within(screen.getByRole('article', { name: 'Reloj de Berlín' })).getByText('UTC+01:00')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Añadir reloj' }))
    fireEvent.change(screen.getByLabelText('Buscar ubicación'), { target: { value: 'GMT+2' } })
    expect(screen.queryByRole('option', { name: /Europe\/Berlin/ })).not.toBeInTheDocument()
  })

  it('cambia de idioma sin recarga, preserva datos anteriores y lo conserva al montar de nuevo', () => {
    const original = { ...defaultPreferences(), theme: 'dark' as const, hourCycle: '12' as const, clocks: [{ id: 'legacy', zone: 'Europe/London', label: 'Mi cliente · Acme' }] }
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(original))
    const write = vi.spyOn(Storage.prototype, 'setItem')
    const first = render(<StrictMode><App /></StrictMode>)
    expect(document.documentElement.lang).toBe('es')
    expect(screen.getByRole('heading', { name: 'Londres' })).toBeInTheDocument()
    expect(write).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }))
    expect(document.documentElement.lang).toBe('en')
    expect(document.title).toBe('Meridiano · World clocks')
    expect(document.documentElement).toHaveAttribute('data-theme', 'dark')
    expect(screen.getByRole('heading', { name: 'London' })).toBeInTheDocument()
    expect(screen.getByText('Mi cliente · Acme')).toBeInTheDocument()
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!)).toEqual({ ...original, language: 'en' })
    first.unmount()
    render(<App />)
    expect(document.documentElement.lang).toBe('en')
    expect(screen.getByRole('button', { name: '12 h' })).toHaveAttribute('aria-pressed', 'true')
    fireEvent.click(screen.getByRole('button', { name: 'ES / EN: Switch to Spanish' }))
    expect(document.title).toBe('Meridiano · Horarios del mundo')
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!)).toEqual({ ...original, language: 'es' })
  })

  it('traduce un error ya visible sin cambiar el instante convertido ni las entradas', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Convertir horario' }))
    fireEvent.change(screen.getByLabelText('Fecha en CDMX'), { target: { value: '2026-12-31' } })
    fireEvent.change(screen.getByLabelText('Hora en CDMX (24 h)'), { target: { value: '23:30' } })
    fireEvent.click(screen.getByRole('button', { name: 'Convertir en todos los relojes' }))
    fireEvent.change(screen.getByLabelText('Fecha en CDMX'), { target: { value: '2022-10-30' } })
    fireEvent.change(screen.getByLabelText('Hora en CDMX (24 h)'), { target: { value: '01:30' } })
    fireEvent.click(screen.getByRole('button', { name: 'Convertir en todos los relojes' }))
    expect(screen.getByRole('alert')).toHaveTextContent('ambigua o no existió')
    fireEvent.click(screen.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }))
    expect(screen.getByRole('alert')).toHaveTextContent('ambiguous or did not exist')
    expect(screen.getByLabelText('Date in Mexico City')).toHaveValue('2022-10-30')
    const tokyo = within(screen.getByRole('article', { name: 'Clock for Tokyo' }))
    expect(tokyo.getByText('14:30')).toBeInTheDocument()
    expect(tokyo.getByText('Friday, January 1, 2027')).toBeInTheDocument()
    expect(tokyo.getByText('+1 day')).toBeInTheDocument()
  })

  it('traduce errores de almacenamiento y permite idioma en memoria sin perder los originales', () => {
    window.localStorage.setItem(STORAGE_KEY, 'invalid original')
    render(<App />)
    expect(screen.getByRole('alert')).toHaveTextContent('datos originales')
    fireEvent.click(screen.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }))
    expect(screen.getByRole('alert')).toHaveTextContent('without changing the original data')
    expect(window.localStorage.getItem(STORAGE_KEY)).toBe('invalid original')
    fireEvent.click(screen.getByRole('button', { name: 'Save this configuration in the app' }))
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!)).toHaveProperty('language', 'en')
  })

  it('traduce el diálogo y busca ciudades por cualquiera de los dos idiomas', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'ES / EN: Cambiar a inglés' }))
    fireEvent.click(screen.getByRole('button', { name: 'Add clock' }))
    const dialog = within(screen.getByRole('dialog'))
    fireEvent.click(dialog.getByRole('button', { name: 'Add clock' }))
    expect(dialog.getByRole('alert')).toHaveTextContent('Select a city or time zone for this clock.')
    fireEvent.change(dialog.getByLabelText('Search location'), { target: { value: 'Londres' } })
    expect(dialog.getByRole('option', { name: 'London · United Kingdom — Europe/London' })).toBeInTheDocument()
    fireEvent.change(dialog.getByLabelText(/City or time zone/), { target: { value: 'Europe/London' } })
    fireEvent.change(dialog.getByLabelText(/Client label/), { target: { value: 'Cliente Español' } })
    fireEvent.click(dialog.getByRole('button', { name: 'Add clock' }))
    expect(screen.getByRole('article', { name: 'Clock for London, Cliente Español' })).toBeInTheDocument()
    expect(screen.getByText('Clock for London added.')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'ES / EN: Switch to Spanish' }))
    expect(screen.getByRole('article', { name: 'Reloj de Londres, Cliente Español' })).toBeInTheDocument()
    expect(screen.getByText('Reloj de Londres añadido.')).toBeInTheDocument()
  })

  it('alterna y conserva el tema explícito sin alterar relojes ni formato', () => {
    const preferences = { ...defaultPreferences(), hourCycle: '12' as const, clocks: [{ id: 'client', zone: 'Asia/Kathmandu', label: 'Mi cliente' }] }
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(preferences))
    const first = render(<StrictMode><App /></StrictMode>)
    expect(document.documentElement).toHaveAttribute('data-theme', 'light')
    fireEvent.click(screen.getByRole('button', { name: 'Cambiar a modo oscuro' }))
    expect(document.documentElement).toHaveAttribute('data-theme', 'dark')
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!)).toEqual({ ...preferences, theme: 'dark' })
    first.unmount()
    render(<App />)
    expect(document.documentElement).toHaveAttribute('data-theme', 'dark')
    expect(screen.getByText('Mi cliente')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Cambiar a modo claro' }))
    expect(document.documentElement).toHaveAttribute('data-theme', 'light')
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!)).toEqual({ ...preferences, theme: 'light' })
  })

  it('usa el tema del sistema sin escribir cuando no hay elección previa', () => {
    vi.mocked(window.matchMedia).mockReturnValue({ ...window.matchMedia(''), matches: true })
    const write = vi.spyOn(Storage.prototype, 'setItem')
    render(<App />)
    expect(document.documentElement).toHaveAttribute('data-theme', 'dark')
    expect(screen.getByRole('button', { name: 'Cambiar a modo claro' })).toBeInTheDocument()
    expect(write).not.toHaveBeenCalled()
  })

  it('respeta el modo claro explícito aunque el sistema esté en oscuro', () => {
    vi.mocked(window.matchMedia).mockReturnValue({ ...window.matchMedia(''), matches: true })
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...defaultPreferences(), theme: 'light' }))
    render(<App />)
    expect(document.documentElement).toHaveAttribute('data-theme', 'light')
  })

  it('permite alternar en memoria y avisa si no puede guardar el tema', () => {
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('Blocked', 'SecurityError') })
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Cambiar a modo oscuro' }))
    expect(document.documentElement).toHaveAttribute('data-theme', 'dark')
    expect(screen.getByRole('alert')).toHaveTextContent('No se pudieron guardar')
    fireEvent.click(screen.getByRole('button', { name: 'Cambiar a modo claro' }))
    expect(document.documentElement).toHaveAttribute('data-theme', 'light')
  })

  it('no sobrescribe preferencias válidas al montar en StrictMode', () => {
    const preferences = { ...defaultPreferences(), clocks: [{ id: 'custom', zone: 'Asia/Kathmandu', label: 'Cliente Nepal' }] }
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(preferences))
    const write = vi.spyOn(Storage.prototype, 'setItem')
    render(<StrictMode><App /></StrictMode>)
    expect(screen.getByText('Cliente Nepal')).toBeInTheDocument()
    expect(screen.queryByRole('article', { name: 'Reloj de Londres' })).not.toBeInTheDocument()
    expect(write).not.toHaveBeenCalled()
  })

  it('permite eliminar todos los relojes y mantiene la lista vacía al abrir de nuevo', () => {
    const first = render(<App />)
    for (const button of screen.getAllByRole('button', { name: /Quitar reloj/ })) fireEvent.click(button)
    expect(screen.getByText('Tu mundo empieza aquí')).toBeInTheDocument()
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!).clocks).toEqual([])
    first.unmount()
    render(<App />)
    expect(screen.getByText('Tu mundo empieza aquí')).toBeInTheDocument()
  })

  it('añade un reloj buscado, edita su etiqueta y persiste el formato', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Añadir reloj' }))
    const dialog = within(screen.getByRole('dialog'))
    fireEvent.change(dialog.getByLabelText('Buscar ubicación'), { target: { value: 'nepal' } })
    fireEvent.change(dialog.getByLabelText(/Ciudad o zona/), { target: { value: 'Asia/Kathmandu' } })
    fireEvent.change(dialog.getByLabelText(/Etiqueta de cliente/), { target: { value: '  Cliente Nepal  ' } })
    fireEvent.click(dialog.getByRole('button', { name: 'Añadir reloj' }))
    expect(screen.getByText('Cliente Nepal')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Editar reloj de Katmandú' }))
    fireEvent.change(screen.getByLabelText(/Etiqueta de cliente/), { target: { value: 'Equipo Nepal' } })
    fireEvent.click(screen.getByRole('button', { name: 'Guardar cambios' }))
    fireEvent.click(screen.getByRole('button', { name: '12 h' }))
    const saved = parsePreferences(window.localStorage.getItem(STORAGE_KEY)!)
    expect(saved.clocks.at(-1)?.label).toBe('Equipo Nepal')
    expect(saved.hourCycle).toBe('12')
  })

  it('exige seleccionar una zona y puede cancelar el diálogo sin guardar', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Añadir reloj' }))
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Añadir reloj' }))
    expect(screen.getByRole('alert')).toHaveTextContent('Selecciona una ciudad')
    fireEvent.click(screen.getByRole('button', { name: 'Cancelar' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(window.localStorage.getItem(STORAGE_KEY)).toBeNull()
  })

  it('convierte, conserva el último instante ante errores y regresa a ahora', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Convertir horario' }))
    fireEvent.change(screen.getByLabelText('Fecha en CDMX'), { target: { value: '2026-12-31' } })
    fireEvent.change(screen.getByLabelText('Hora en CDMX (24 h)'), { target: { value: '23:30' } })
    fireEvent.click(screen.getByRole('button', { name: 'Convertir en todos los relojes' }))
    const tokyo = within(screen.getByRole('article', { name: 'Reloj de Tokio' }))
    expect(tokyo.getByText('14:30')).toBeInTheDocument()
    expect(tokyo.getByText('+1 día')).toBeInTheDocument()
    expect(tokyo.getByText(/1 de enero de 2027/)).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Fecha en CDMX'), { target: { value: '' } })
    fireEvent.click(screen.getByRole('button', { name: 'Convertir en todos los relojes' }))
    expect(screen.getByRole('alert')).toHaveTextContent('fecha y una hora completas')
    expect(tokyo.getByText('14:30')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Volver a ahora' }))
    expect(screen.getByRole('button', { name: 'Ahora' })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('timer')).toBeInTheDocument()
    expect(screen.queryByLabelText('Fecha en CDMX')).not.toBeInTheDocument()
  })

  it('no reemplaza datos dañados ni con interacción hasta un guardado explícito', () => {
    window.localStorage.setItem(STORAGE_KEY, 'broken original')
    render(<App />)
    expect(screen.getByRole('alert')).toHaveTextContent('datos originales')
    fireEvent.click(screen.getByRole('button', { name: '12 h' }))
    expect(window.localStorage.getItem(STORAGE_KEY)).toBe('broken original')
    fireEvent.click(screen.getByRole('button', { name: 'Guardar esta configuración en la app' }))
    expect(parsePreferences(window.localStorage.getItem(STORAGE_KEY)!).hourCycle).toBe('12')
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
  })

  it('mantiene cambios en memoria y avisa cuando falla LocalStorage', () => {
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('Full', 'QuotaExceededError') })
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Quitar reloj de Tokio' }))
    expect(screen.getByRole('alert')).toHaveTextContent('No se pudieron guardar')
    expect(screen.queryByRole('article', { name: 'Reloj de Tokio' })).not.toBeInTheDocument()
  })

  it('comparte un único reloj vivo, lo pausa al convertir y limpia el intervalo', () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-15T15:30:00Z'))
    const media = window.matchMedia('')
    vi.mocked(window.matchMedia).mockImplementation(query => ({ ...media, media: query, matches: query === '(prefers-reduced-motion: reduce)' }))
    const clearInterval = vi.spyOn(window, 'clearInterval')
    const view = render(<App />)
    expect(screen.getByRole('timer')).toHaveTextContent('09:30:00')
    fireEvent.click(screen.getByRole('button', { name: 'Convertir horario' }))
    expect(clearInterval).toHaveBeenCalled()
    expect(vi.getTimerCount()).toBe(0)
    fireEvent.click(screen.getByRole('button', { name: 'Volver a ahora' }))
    expect(vi.getTimerCount()).toBe(1)
    view.unmount()
    expect(vi.getTimerCount()).toBe(0)
    vi.useRealTimers()
  })
})
